BOX_IMAGE = 'centos/7'




HADOOP_NET = "10.0.0"
HADOOP_NETWORK = "nah.hadoop"
IPA_ADM_IP= HADOOP_NET + ".9"


Vagrant.configure("2") do |config|


  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    #This speeds up recreating containers
    v.linked_clone = true
  end

  #Require vagrant plugin install vagrant-vbguest
  #Require vagrant plugin install vagrant-sshfs
  config.vm.synced_folder ".", "/vagrant", type: "sshfs"

  
  config.vm.provision :shell,
                         inline: "yum update -y",
                         name: "yum update"

  config.vm.provision :shell,
                      inline: "echo -e 'vagrant123\nvagrant123'|  passwd vagrant",
                      name: "vagrant password set"

  #Vagrant places hostname in /etc/hosts. This cause our scripts to get the wrong IP address. Remove it
  config.vm.provision "shell", inline: "cp /etc/hosts /etc/hosts.orig", name: "backing up /etc/hosts"
  config.vm.provision "shell", inline: "grep localhost /etc/hosts.orig > /etc/hosts", name: "Removing hostname from hosts", run: "always"

  config.vm.provision "shell",
                      name: "Backing up resolv.conf if not done already",
                      inline: "[ -f /etc/resolv.conf.orig ] || cp /etc/resolv.conf /etc/resolv.conf.orig", run: "always"

  config.vm.provision "shell",
                      name: "Appending search domain "+HADOOP_NETWORK+" to /etc/resolv.conf",
                      inline: "grep '^search .*"+HADOOP_NETWORK+".*$' /etc/resolv.conf || sed -i -E 's/^(search .*)$/\1 "+HADOOP_NETWORK+"/' /etc/resolv.conf", run: "always"

  config.vm.provision "shell",
                      name: "Appending ipa-adm DNS server "+IPA_ADM_IP+" to /etc/resolv.conf",
                      inline: "grep "+IPA_ADM_IP+" /etc/resolv.conf || echo 'nameserver "+IPA_ADM_IP+"' >>/etc/resolv.conf", run: "always"


  # They should all run the global bootstrap
  #config.vm.provision "shell", inline: $bootstrap, name: "all/bootstrap.sh"


  # FreeIPA and nfs server
  config.vm.define "nah-adm" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-adm." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: IPA_ADM_IP

    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

    subconfig.vm.provision :shell, path: "Install_IPA.sh", name: 'Install IPA'

  end

  # Ambari Server
  config.vm.define "nah-abri" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-abri." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".113"

    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    subconfig.vm.network "forwarded_port", guest: 8080, host: 8080 # Ambari

    # Ambari must own this folder, and it does not do so by default.
    subconfig.vm.provision :shell,
                           inline: "(id ambari && chown ambari:ambari /var/run/ambari-server/ -R) || true",
                           name: "Owning /var/run/ambari-server/",
                           run: "always"
  end


  # DataNodes
  config.vm.define "nah-data-001" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-data-001." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".11"
  end


  config.vm.define "nah-data-002" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-data-002." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".12"


    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

  end


  config.vm.define "nah-data-003" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-data-003." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".13"

    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

  end


  config.vm.define "nah-hdfs-001" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-hdfs-001." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".101"
  end


  config.vm.define "nah-zkpr-001" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-zpkr-001." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".104"
  end


  config.vm.define "nah-yarn-001" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-yarn-001." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".114"
  end


  config.vm.define "nah-hist" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-hist." + HADOOP_NETWORK
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".116"
  end


  config.vm.define "nah-proj-000" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nah-proj-000.kach.network"
    subconfig.vm.network :private_network, ip: HADOOP_NET + ".60"
  end


end

