#!/usr/bin/expect
# https://community.hortonworks.com/articles/74332/how-to-automate-ldap-sync-for-ambari-1.html

set timeout 200
set principal [lindex $argv 0]
set pass [lindex $argv 1]
set server [lindex $argv 2]
set keytab [lindex $argv 3]

spawn ipa-getkeytab --server=$server --principal=$principal --keytab=$keytab --password
expect "New Principal Password:"  { send "$pass\n" }
expect "Verify Principal Password: " { send "$pass\n" }
expect eof

